export const colors = {
  bone: "var(--color-bone)",
  paper: "var(--color-paper)",
  rule: "var(--color-rule)",
  ruleStrong: "var(--color-rule-strong)",
  ink: "var(--color-ink)",
  inkSoft: "var(--color-ink-soft)",
  muted: "var(--color-muted)",
  mutedSoft: "var(--color-muted-soft)",
  gain: "var(--color-gain)",
  gainSoft: "var(--color-gain-soft)",
  loss: "var(--color-loss)",
  lossSoft: "var(--color-loss-soft)",
  warn: "var(--color-warn)",
  warnSoft: "var(--color-warn-soft)",
  accent: "var(--color-accent)",
  accentSoft: "var(--color-accent-soft)",
} as const;
